export const salesTableHeaders = [
  'sale_id',
  'date',
  'supplier_article',
  'brand',
  'subject',
  'total_price',
  'discount_percent',
  'finished_price'
]

export const salesTableLabels = {
  sale_id: 'ID продажи',
  date: 'Дата продажи',
  supplier_article: 'Артикул поставщика',
  brand: 'Бренд',
  subject: 'Предмет',
  total_price: 'Сумма продажи',
  discount_percent: 'Скидка, %',
  finished_price: 'Итоговая цена',
  for_pay: 'К выплате',
  warehouse_name: 'Склад',
  g_number: 'Номер продажи',
  last_change_date: 'Дата изменения',
  tech_size: 'Размер',
  barcode: 'Штрихкод',
  category: 'Категория',
  country_name: 'Страна',
  income_id: 'ID прихода',
  is_realization: 'Реализация',
  is_storno: 'Сторно',
  is_supply: 'Поставка',
  nm_id: 'NM ID',
  oblast_okrug_name: 'Округ',
  odid: 'ODID',
  price_with_disc: 'Цена со скидкой',
  promo_code_discount: 'Скидка по промокоду',
  region_name: 'Регион',
  spp: 'СПП',
} 